package fiware

import (
	"github.com/warpcomdev/fiware/internal/serialize"
)

// Autogenerated file - DO NOT EDIT

func (x Vertical) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x Vertical) Serialize(s serialize.Serializer) {
	s.KeyString("name", x.Name)
	s.KeyString("subservice", x.Subservice)
	if len(x.EntityTypes) > 0 {
		s.BeginList("entityTypes")
		for _, y := range x.EntityTypes {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.Entities) > 0 {
		s.BeginList("entities")
		for _, y := range x.Entities {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.ServiceMappings) > 0 {
		s.BeginList("serviceMappings")
		for _, y := range x.ServiceMappings {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.Suscriptions) > 0 {
		s.BeginList("suscriptions")
		for _, y := range x.Suscriptions {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.Tables) > 0 {
		s.BeginList("tables")
		for _, y := range x.Tables {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.Services) > 0 {
		s.BeginList("services")
		for _, y := range x.Services {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.Devices) > 0 {
		s.BeginList("devices")
		for _, y := range x.Devices {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.Rules) > 0 {
		s.BeginList("rules")
		for _, y := range x.Rules {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.Projects) > 0 {
		s.BeginList("projects")
		for _, y := range x.Projects {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.Panels) > 0 {
		s.BeginBlock("panels")
		for k, v := range x.Panels {
			s.KeyRaw(k, v, false)
		}
		s.EndBlock()
	}
	if len(x.Verticals) > 0 {
		s.BeginBlock("verticals")
		for k, v := range x.Verticals {
			s.KeyRaw(k, v, false)
		}
		s.EndBlock()
	}
}

func (x EntityType) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x EntityType) Serialize(s serialize.Serializer) {
	s.KeyString("entityID", x.ID)
	s.KeyString("entityType", x.Type)
	s.BeginList("attrs")
	for _, y := range x.Attrs {
		s.BeginBlock("")
		s.Serialize(y)
		s.EndBlock()
	}
	s.EndList()
}

func (x Attribute) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x Attribute) Serialize(s serialize.Serializer) {
	s.KeyString("name", x.Name)
	s.KeyString("type", x.Type)
	if len(x.Value) > 0 {
		s.KeyRaw("value", x.Value, true)
	}
	if len(x.Metadatas) > 0 {
		s.KeyRaw("metadatas", x.Metadatas, true)
	}
}

func (x Entity) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x Entity) Serialize(s serialize.Serializer) {
	s.KeyString("entityID", x.ID)
	s.KeyString("entityType", x.Type)
	s.BeginBlock("attrs")
	for k, v := range x.Attrs {
		s.KeyRaw(k, v, true)
	}
	s.EndBlock()
	if len(x.MetaDatas) > 0 {
		s.BeginBlock("metadatas")
		for k, v := range x.MetaDatas {
			s.KeyRaw(k, v, true)
		}
		s.EndBlock()
	}
}

func (x ServiceMapping) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x ServiceMapping) Serialize(s serialize.Serializer) {
	if x.OriginalService != "" {
		s.KeyString("originalService", x.OriginalService)
	}
	if x.NewService != "" {
		s.KeyString("newService", x.NewService)
	}
	s.BeginList("servicePathMappings")
	for _, y := range x.ServicePathMappings {
		s.BeginBlock("")
		s.Serialize(y)
		s.EndBlock()
	}
	s.EndList()
}

func (x ServicePathMapping) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x ServicePathMapping) Serialize(s serialize.Serializer) {
	if x.OriginalServicePath != "" {
		s.KeyString("originalServicePath", x.OriginalServicePath)
	}
	if x.NewServicePath != "" {
		s.KeyString("newServicePath", x.NewServicePath)
	}
	s.BeginList("entityMappings")
	for _, y := range x.EntityMappings {
		s.BeginBlock("")
		s.Serialize(y)
		s.EndBlock()
	}
	s.EndList()
}

func (x EntityMapping) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x EntityMapping) Serialize(s serialize.Serializer) {
	if x.OriginalEntityId != "" {
		s.KeyString("originalEntityId", x.OriginalEntityId)
	}
	if x.NewEntityId != "" {
		s.KeyString("newEntityId", x.NewEntityId)
	}
	if x.OriginalEntityType != "" {
		s.KeyString("originalEntityType", x.OriginalEntityType)
	}
	if x.NewEntityType != "" {
		s.KeyString("newEntityType", x.NewEntityType)
	}
	s.BeginList("attributeMappings")
	for _, y := range x.AttributeMappings {
		s.BeginBlock("")
		s.Serialize(y)
		s.EndBlock()
	}
	s.EndList()
}

func (x AttributeMapping) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x AttributeMapping) Serialize(s serialize.Serializer) {
	if x.OriginalAttributeName != "" {
		s.KeyString("originalAttributeName", x.OriginalAttributeName)
	}
	if x.OriginalAttributeType != "" {
		s.KeyString("originalAttributeType", x.OriginalAttributeType)
	}
	if x.NewAttributeName != "" {
		s.KeyString("newAttributeName", x.NewAttributeName)
	}
	if x.NewAttributeType != "" {
		s.KeyString("newAttributeType", x.NewAttributeType)
	}
}

func (x Suscription) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x Suscription) Serialize(s serialize.Serializer) {
	s.KeyString("description", x.Description)
	if x.Status != "" {
		s.KeyString("status", x.Status)
	}
	if x.Expires != "" {
		s.KeyString("expires", x.Expires)
	}
	s.BeginBlock("notification")
	x.Notification.Serialize(s)
	s.EndBlock()
	s.BeginBlock("subject")
	x.Subject.Serialize(s)
	s.EndBlock()
	x.SuscriptionStatus.Serialize(s)
}

func (x Notification) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x Notification) Serialize(s serialize.Serializer) {
	if len(x.Attrs) > 0 {
		s.BeginList("attrs")
		for _, y := range x.Attrs {
			s.String(y)
		}
		s.EndList()
	}
	if len(x.ExceptAttrs) > 0 {
		s.BeginList("exceptAttrs")
		for _, y := range x.ExceptAttrs {
			s.String(y)
		}
		s.EndList()
	}
	s.KeyString("attrsFormat", x.AttrsFormat)
	if !x.HTTP.IsEmpty() {
		s.BeginBlock("http")
		x.HTTP.Serialize(s)
		s.EndBlock()
	}
	if !x.HTTPCustom.IsEmpty() {
		s.BeginBlock("httpCustom")
		x.HTTPCustom.Serialize(s)
		s.EndBlock()
	}
	if x.OnlyChangedAttrs {
		s.KeyBool("onlyChangedAttrs", x.OnlyChangedAttrs)
	}
	if x.Covered {
		s.KeyBool("covered", x.Covered)
	}
	x.NotificationStatus.Serialize(s)
}

func (x NotificationHTTP) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x NotificationHTTP) Serialize(s serialize.Serializer) {
	s.KeyString("url", x.URL)
}

func (x NotificationCustom) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x NotificationCustom) Serialize(s serialize.Serializer) {
	s.KeyString("url", x.URL)
	if len(x.Headers) > 0 {
		s.BeginBlock("headers")
		for k, v := range x.Headers {
			s.KeyString(k, v)
		}
		s.EndBlock()
	}
	if len(x.Payload) > 0 {
		s.KeyRaw("payload", x.Payload, false)
	}
	if x.Method != "" {
		s.KeyString("method", x.Method)
	}
}

func (x NotificationStatus) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x NotificationStatus) Serialize(s serialize.Serializer) {
	if x.LastFailure != "" {
		s.KeyString("lastFailure", x.LastFailure)
	}
	if x.LastFailureReason != "" {
		s.KeyString("lastFailureReason", x.LastFailureReason)
	}
	if x.LastNotification != "" {
		s.KeyString("lastNotification", x.LastNotification)
	}
	if x.LastSuccess != "" {
		s.KeyString("lastSuccess", x.LastSuccess)
	}
	if x.LastSuccessCode != 0 {
		s.KeyInt("lastSuccessCode", x.LastSuccessCode)
	}
	if x.FailsCounter != 0 {
		s.KeyInt("failsCounter", x.FailsCounter)
	}
	if x.TimesSent != 0 {
		s.KeyInt("timesSent", x.TimesSent)
	}
}

func (x Subject) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x Subject) Serialize(s serialize.Serializer) {
	s.BeginBlock("condition")
	x.Condition.Serialize(s)
	s.EndBlock()
	s.BeginList("entities")
	for _, y := range x.Entities {
		s.BeginBlock("")
		s.Serialize(y)
		s.EndBlock()
	}
	s.EndList()
}

func (x SubjectCondition) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x SubjectCondition) Serialize(s serialize.Serializer) {
	if len(x.Attrs) > 0 {
		s.BeginList("attrs")
		for _, y := range x.Attrs {
			s.String(y)
		}
		s.EndList()
	}
	if !x.Expression.IsEmpty() {
		s.BeginBlock("expression")
		x.Expression.Serialize(s)
		s.EndBlock()
	}
}

func (x SubjectExpression) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x SubjectExpression) Serialize(s serialize.Serializer) {
	if x.Q != "" {
		s.KeyString("q", x.Q)
	}
}

func (x SubjectEntity) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x SubjectEntity) Serialize(s serialize.Serializer) {
	if x.IdPattern != "" {
		s.KeyString("idPattern", x.IdPattern)
	}
	s.KeyString("type", x.Type)
}

func (x SuscriptionStatus) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x SuscriptionStatus) Serialize(s serialize.Serializer) {
	if x.ID != "" {
		s.KeyString("id", x.ID)
	}
}

func (x Table) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x Table) Serialize(s serialize.Serializer) {
	s.KeyString("name", x.Name)
	s.BeginList("columns")
	for _, y := range x.Columns {
		s.BeginBlock("")
		s.Serialize(y)
		s.EndBlock()
	}
	s.EndList()
	s.BeginList("primaryKey")
	for _, y := range x.PrimaryKey {
		s.String(y)
	}
	s.EndList()
	s.BeginList("indexes")
	for _, y := range x.Indexes {
		s.BeginBlock("")
		s.Serialize(y)
		s.EndBlock()
	}
	s.EndList()
	s.KeyBool("lastdata", x.LastData)
}

func (x TableColumn) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x TableColumn) Serialize(s serialize.Serializer) {
	s.KeyString("name", x.Name)
	s.KeyString("type", x.Type)
	if x.NotNull {
		s.KeyBool("notNull", x.NotNull)
	}
	if x.Default != "" {
		s.KeyString("default", x.Default)
	}
}

func (x TableIndex) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x TableIndex) Serialize(s serialize.Serializer) {
	s.KeyString("name", x.Name)
	s.BeginList("columns")
	for _, y := range x.Columns {
		s.String(y)
	}
	s.EndList()
	if x.Geometry {
		s.KeyBool("geometry", x.Geometry)
	}
}

func (x Service) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x Service) Serialize(s serialize.Serializer) {
	s.KeyString("resource", x.Resource)
	s.KeyString("apikey", x.APIKey)
	s.KeyString("entity_type", x.EntityType)
	if x.Description != "" {
		s.KeyString("description", x.Description)
	}
	s.KeyString("protocol", x.Protocol)
	if x.Transport != "" {
		s.KeyString("transport", x.Transport)
	}
	if x.Timestamp {
		s.KeyBool("timestamp", x.Timestamp)
	}
	if len(x.ExplicitAttrs) > 0 {
		s.KeyRaw("explicitAttrs", x.ExplicitAttrs, false)
	}
	if len(x.InternalAttributes) > 0 {
		s.BeginList("internal_attributes")
		for _, y := range x.InternalAttributes {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	s.BeginList("attributes")
	for _, y := range x.Attributes {
		s.BeginBlock("")
		s.Serialize(y)
		s.EndBlock()
	}
	s.EndList()
	if len(x.Lazy) > 0 {
		s.BeginList("lazy")
		for _, y := range x.Lazy {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.StaticAttributes) > 0 {
		s.BeginList("static_attributes")
		for _, y := range x.StaticAttributes {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.Commands) > 0 {
		s.BeginList("commands")
		for _, y := range x.Commands {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if x.ExpressionLanguage != "" {
		s.KeyString("expressionLanguage", x.ExpressionLanguage)
	}
	x.GroupStatus.Serialize(s)
}

func (x DeviceAttribute) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x DeviceAttribute) Serialize(s serialize.Serializer) {
	s.KeyString("object_id", x.ObjectId)
	s.KeyString("name", x.Name)
	if x.Type != "" {
		s.KeyString("type", x.Type)
	}
	if len(x.Value) > 0 {
		s.KeyRaw("value", x.Value, false)
	}
	if x.Expression != "" {
		s.KeyString("expression", x.Expression)
	}
	if x.EntityName != "" {
		s.KeyString("entity_name", x.EntityName)
	}
	if x.EntityType != "" {
		s.KeyString("entity_type", x.EntityType)
	}
}

func (x DeviceCommand) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x DeviceCommand) Serialize(s serialize.Serializer) {
	if x.ObjectId != "" {
		s.KeyString("object_id", x.ObjectId)
	}
	if x.Name != "" {
		s.KeyString("name", x.Name)
	}
	if x.Type != "" {
		s.KeyString("type", x.Type)
	}
	if x.Value != "" {
		s.KeyString("value", x.Value)
	}
	if len(x.MQTT) > 0 {
		s.KeyRaw("mqtt", x.MQTT, false)
	}
}

func (x GroupStatus) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x GroupStatus) Serialize(s serialize.Serializer) {
	if x.ID != "" {
		s.KeyString("_id", x.ID)
	}
	if x.V != 0 {
		s.KeyInt("__v", x.V)
	}
	if x.IOTAgent != "" {
		s.KeyString("iotagent", x.IOTAgent)
	}
	if x.ServicePath != "" {
		s.KeyString("service_path", x.ServicePath)
	}
	if x.Service != "" {
		s.KeyString("service", x.Service)
	}
	if x.CBHost != "" {
		s.KeyString("cbHost", x.CBHost)
	}
}

func (x Device) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x Device) Serialize(s serialize.Serializer) {
	s.KeyString("device_id", x.DeviceId)
	if x.APIKey != "" {
		s.KeyString("apikey", x.APIKey)
	}
	if x.EntityName != "" {
		s.KeyString("entity_name", x.EntityName)
	}
	s.KeyString("entity_type", x.EntityType)
	if x.Polling {
		s.KeyBool("polling", x.Polling)
	}
	s.KeyString("transport", x.Transport)
	if x.Timestamp {
		s.KeyBool("timestamp", x.Timestamp)
	}
	if x.Endpoint != "" {
		s.KeyString("endpoint", x.Endpoint)
	}
	if len(x.Attributes) > 0 {
		s.BeginList("attributes")
		for _, y := range x.Attributes {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.Lazy) > 0 {
		s.BeginList("lazy")
		for _, y := range x.Lazy {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.Commands) > 0 {
		s.BeginList("commands")
		for _, y := range x.Commands {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	if len(x.StaticAttributes) > 0 {
		s.BeginList("static_attributes")
		for _, y := range x.StaticAttributes {
			s.BeginBlock("")
			s.Serialize(y)
			s.EndBlock()
		}
		s.EndList()
	}
	s.KeyString("protocol", x.Protocol)
	if x.ExpressionLanguage != "" {
		s.KeyString("expressionLanguage", x.ExpressionLanguage)
	}
	if len(x.ExplicitAttrs) > 0 {
		s.KeyRaw("explicitAttrs", x.ExplicitAttrs, false)
	}
	x.DeviceStatus.Serialize(s)
}

func (x DeviceStatus) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x DeviceStatus) Serialize(s serialize.Serializer) {
	if x.Service != "" {
		s.KeyString("service", x.Service)
	}
	if x.ServicePath != "" {
		s.KeyString("service_path", x.ServicePath)
	}
}

func (x Rule) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x Rule) Serialize(s serialize.Serializer) {
	s.KeyString("name", x.Name)
	if x.Description != "" {
		s.KeyString("description", x.Description)
	}
	if x.Misc != "" {
		s.KeyString("misc", x.Misc)
	}
	if x.Text != "" {
		s.KeyString("text", x.Text)
	}
	if x.VR != "" {
		s.KeyString("VR", x.VR)
	}
	if len(x.Action) > 0 {
		s.KeyRaw("action", x.Action, false)
	}
	if len(x.NoSignal) > 0 {
		s.KeyRaw("nosignal", x.NoSignal, false)
	}
	x.RuleStatus.Serialize(s)
}

func (x RuleStatus) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x RuleStatus) Serialize(s serialize.Serializer) {
	if x.Subservice != "" {
		s.KeyString("subservice", x.Subservice)
	}
	if x.Service != "" {
		s.KeyString("service", x.Service)
	}
	if x.ID != "" {
		s.KeyString("_id", x.ID)
	}
}

func (x Project) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x Project) Serialize(s serialize.Serializer) {
	s.KeyBool("is_domain", x.IsDomain)
	if x.Description != "" {
		s.KeyString("description", x.Description)
	}
	if len(x.Tags) > 0 {
		s.KeyRaw("tags", x.Tags, false)
	}
	s.KeyBool("enabled", x.Enabled)
	s.KeyString("id", x.ID)
	if x.ParentId != "" {
		s.KeyString("parent_id", x.ParentId)
	}
	if x.DomainId != "" {
		s.KeyString("domain_id", x.DomainId)
	}
	s.KeyString("name", x.Name)
	x.ProjectStatus.Serialize(s)
}

func (x ProjectStatus) MarshalJSON() ([]byte, error) {
	return serialize.MarshalJSON(x)
}

func (x ProjectStatus) Serialize(s serialize.Serializer) {
	if len(x.Links) > 0 {
		s.KeyRaw("links", x.Links, false)
	}
}
